### PR TITLE
Implemented signInWithEmailAndPassword()

### PR DESCRIPTION
**Pull request by CiriousJoker**

### CODE REVIEW

**Comment by CiriousJoker** [comment]
@cla-bot check

**Review by Sese-Schneider — CHANGES_REQUESTED** [review]
Thank you for your PR!

In order to merge this, please update the version number, the description in `README.md` and `CHANGELOG.md`.
I will test and merge this if it works 👍

**Comment by Sese-Schneider** [comment]
@cla-bot check

**Comment by Sese-Schneider** [comment]
@CiriousJoker on the first view, this looks good to me. However, I couldn't test it and confirm its working.
I will do it as soon as I've got time, however, this could take some time as I'm on vacation (and the only maintainer actively working on the repo). Hope this isn't super urgent either 😓

**Comment by CiriousJoker** [comment]
I mean it does work for me, so I'm happy either way :)

Have fun on vacation!

**Review by Sese-Schneider — APPROVED** [review]
LGTM & Tested, thank you for your PR.
Will deploy as soon as this is merged by you @CiriousJoker

**Comment by creativecreatorormaybenot** [comment]
@Sese-Schneider 

@CiriousJoker cannot merge because you need write access afaic.

**Comment by Sese-Schneider** [comment]
@creativecreatorormaybenot oops thx :D

**Pull request merged**
